spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: garagepro247@gmail.com
    password: arrp slhl nunx hah
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com

server:
  port: 8888
